{% set version = "0.1.5" %}

package:
  name: runipy
  version: {{ version }}

source:
  fn: runipy-{{ version }}.tar.gz
  url: https://pypi.python.org/packages/source/r/runipy/runipy-{{ version }}.tar.gz
  md5: afef5be6b8103b9d7f5ba9d086f25d53

build:
  noarch: python
  number: 2
  entry_points:
    - runipy = runipy.main:main

requirements:
  host:
    - pip
    - python
    - setuptools
    - jinja2 >=2.7.2
    - pygments >=1.6
    - ipython >=2.3.1
    - pyzmq >=14.1.0
    - ipykernel >=4.0.0
    - nbconvert >=4.0.0
    - nbformat >=4.0.0

  run:
    - python
    - jinja2 >=2.7.2
    - pygments >=1.6
    - ipython >=2.3.1
    - pyzmq >=14.1.0
    - ipykernel >=4.0.0
    - nbconvert >=4.0.0
    - nbformat >=4.0.0

test:
  imports:
    - runipy

  commands:
    - runipy --help

about:
  home: https://github.com/paulgb/runipy
  license: BSD 2-Clause
  license_file: LICENSE
  summary: 'Run IPython notebooks from the command line'

extra:
  recipe-maintainers:
    - jakirkham
    - paulgb
