appveyor:
  secure: {BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: qBekLGmWYpL29ZKgiJaGfizzECZXVhNGi2lxXdCSp68jADXWprxP+OOO2Ub6WyPYFbB5VscZg/a3NeCqcIOGq+ph1DN3sJg0VuaD4sq/6xxbehZUJstq92ei6MnJMo0D+FIjEAlURzNwVvkNkU3qurjqGpt4OVP8kU/2OWMYKOhyC1Mi6WRemCLWDJDpL+hcn69++mawL+m/QHLP01wVk+it4lyCL4ZwY4eujwZJoyZXfCd/0vChuBTaDgK9LjxGCve1nFPjpMjvADvcHwTiNDcNp/ZsybpnCNoU1rGDDY8MaR10eTH2RneyVsOj0xj7w75ZYBuJj/Y3Sze0xMgMiEacKc+8MnxAAlECyhbojtMgn1ff0aaCnHFRahTT+xS+7zR8RIvUCnXH++huRTAj3CgJGcMEut07bV+lZr3qloU0EBr9C45zk++IWgrLTGOXfRc4MC5q0sb8/p8kzpvQbHnh32aOvN9wswIH9KosBAwKIYhULMs0YEeg91Zz6xXNCoJF/2ZVlRKnv5gw4OQKnASfv+fo+wf6N+jGRtJgRyFRnDZHelQTUlIbrfv66oWad+fybW6SYxvZaeOyMWVGKU5NmejObMhwKLTTNZUQCf7G8eoMe7cj9FG95W0c8mJPaIUUo758kNf7Il9wNhUjFIjIYsEb14XK1bDI8BT484Q=}
